name: MuseScore Export
on:
  push:
    paths:
      - '**/*.mscx'
      - '!**/Excerpts/**'
      - '!WIP/**'
jobs:
  export-scores:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Locate files
      id: getfile
      run: |
        git fetch origin ${{ github.event.before }}:${{ github.event.before }}
        mscxfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.mscx$' | grep -v '/Excerpts/' | tr '\n' ' ')
        printf 'MSCXFILES=%s\n' "$mscxfiles" >> $GITHUB_ENV

    - name: Install MuseScore
      run: |
        wget -q https://github.com/musescore/MuseScore/releases/download/v4.2.0/MuseScore-4.2.0.233521125-x86_64.AppImage
        chmod +x MuseScore-4.2.0.233521125-x86_64.AppImage
        ./MuseScore-4.2.0.233521125-x86_64.AppImage --appimage-extract

    - name: Install dependencies
      run: |
            sudo apt-get update
            sudo apt-get install -y libjack-jackd2-0 libegl1-mesa

    - name: Export scores
      run: |
        sudo apt-get install -y xvfb zip
        for file in ${{ env.MSCXFILES }}
        do      
          # Extract project name and directory
          project_dir=$(dirname "$file")
          project_name=$(basename "$file" .mscx)

          # Remove old build files in the directory
          rm -rf "$project_dir/build"
          mkdir -p "$project_dir/build"

          # Run the batch job to create all parts
           xvfb-run -a ./squashfs-root/AppRun -P -o $project_dir/build/${project_name}.pdf $file
        done

    - name: Split PDFs
      run: |
        sudo apt-get install -y poppler-utils
        for file in ${{ env.MSCXFILES }}
        do
          project_dir=$(dirname "$file")
          project_name=$(basename "$file" .mscx)
          abbreviated_title=$project_name
          if [ -f "$project_dir/config.yaml" ]; then
            abbreviated_title=$(yq e '.abbreviated_title' "$project_dir/config.yaml" || echo "$project_name")
          fi
          mkdir -p "$project_dir/build/parts"
          mv "$project_dir/build/${project_name}.pdf" "$project_dir/build/${abbreviated_title}.pdf"
          pdfseparate "$project_dir/build/${abbreviated_title}.pdf" "$project_dir/build/parts/${abbreviated_title}_%d.pdf"
          start_page=1
          part_number=1
          total_pages=$(pdfinfo "$project_dir/build/${abbreviated_title}.pdf" | awk '/Pages:/ {print $2}')
          for ((page=1; page<=total_pages; page++))
          do
            if pdftotext "$project_dir/build/parts/${abbreviated_title}_${page}.pdf" - | grep -q 'arr. Brandon Park'; then
              if [ $page -ne $start_page ]; then
                part_name=$(pdftotext "$project_dir/build/parts/${abbreviated_title}_${start_page}.pdf" - | head -n 1 | sed 's/ /_/g')
                files_to_unite=()
                for ((i=start_page; i<page; i++)); do
                  files_to_unite+=("$project_dir/build/parts/${abbreviated_title}_${i}.pdf")
                done
                pdfunite "${files_to_unite[@]}" "$project_dir/build/${abbreviated_title}_${part_name}.pdf"
                ((part_number++))
              fi
              start_page=$page
            fi
          done
          part_name=$(pdftotext "$project_dir/build/parts/${abbreviated_title}_${start_page}.pdf" - | head -n 1 | sed 's/ /_/g')
          files_to_unite=()
          for ((i=start_page; i<=total_pages; i++)); do
            files_to_unite+=("$project_dir/build/parts/${abbreviated_title}_${i}.pdf")
          done
          pdfunite "${files_to_unite[@]}" "$project_dir/build/${abbreviated_title}_${part_name}.pdf"
          rm -rf "$project_dir/build/parts"
        done

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Sort parts
      run: |
        for file in ${{ env.MSCXFILES }}
        do
          project_dir=$(dirname "$file")
          project_name=$(basename "$file" .mscx)
          abbreviated_title=$project_name
          if [ -f "$project_dir/config.yaml" ]; then
            abbreviated_title=$(yq e '.abbreviated_title' "$project_dir/config.yaml" || echo "$project_name")
          fi
          if [ -f "parts.yaml" ]; then
            for category in $(yq e 'keys | .[]' "parts.yaml"); do
              mkdir -p "$project_dir/build/$category"
              yq e '.["'$category'"][]' "parts.yaml" | while read -r part; do
                part=$(echo "$part" | tr -d '"' | sed 's/ /_/g') # remove quotes and replace whitespace with underscores
                mv "$project_dir/build/${abbreviated_title}_${part}.pdf" "$project_dir/build/$category/${abbreviated_title}_${part}.pdf" 2>/dev/null || true
              done
            done
          fi
        done

    - name: Create zip files
      run: |
        for file in ${{ env.MSCXFILES }}
        do
          project_dir=$(dirname "$file")
          project_name=$(basename "$file" .mscx)
          cd "$project_dir/build"
          zip -r "$GITHUB_WORKSPACE/$project_name.zip" *
          cd "$GITHUB_WORKSPACE"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: parts
        path: '*.zip'

    - name: Upload to Google Drive
      run: |
        for file in ${{ env.MSCXFILES }}
        do
          project_dir=$(dirname "$file")
          project_name=$(basename "$file" .mscx)
          gdrive_link=$(yq e '.google_drive_link' "$project_dir/config.yaml")
          if [ -n "$gdrive_link" ]; then
            folder_id=$(echo "$gdrive_link" | grep -oP 'folders/\K[^/]+')
            echo "FOLDER_ID=$folder_id" >> $GITHUB_ENV
            echo "PROJECT_DIR=$project_dir" >> $GITHUB_ENV

            # Upload to Google Drive
            uses: gdrive-org/drive-upload-action@v1
            with:
              serviceAccount: ${{ secrets.GDRIVE_SA_FILE }}
              folderId: ${{ env.FOLDER_ID }}
              uploadPath: "${{ env.PROJECT_DIR }}/build"
          fi
        done